# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160819_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='junior',
            field=models.BooleanField(default=True),
        ),
    ]
